# Generated by Django 4.2.7 on 2026-04-18 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_asset_alter_user_managers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asset',
        ),
    ]
